name: Build/release

on:
  push:
    branches:
      - main
      - build-and-release

jobs:
  release:
    runs-on: windows-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      # Install Python to satisfy node-gyp dependencies
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'  # Recommended version range for node-gyp

      - name: Configure Git with GitHub Actions Bot
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "<>"

      - name: Increment version number
        run: |
          yarn version --patch
          git add .
          git commit -m "Release version $NEW_VERSION"
          git push origin --follow-tags
      
      - name: Save version number
        id: increment_version
        shell: cmd
        run: |
          FOR /F "delims=" %%A IN ('node -p "require('./package.json').version"') DO SET NEW_VERSION=%%A
          echo ::set-output name=new_version::%NEW_VERSION%

      - name: Build/release Electron app
        uses: samuelmeuli/action-electron-builder@v1
        with:
          # GitHub token, automatically provided to the action
          # (No need to define this secret in the repo settings)
          github_token: ${{ secrets.github_token }}
          # args: "--dir"

      - name: Upload installer
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.github_token }}
          tag_name: "v${{ steps.increment_version.outputs.new_version }}"
          body: |
            Automated release for version v${{ steps.increment_version.outputs.new_version }}"
            - Installer included
          make_latest: true
          files: |
            build/*.exe
  